FROM php:8.4-apache
# Instalar dependencias necesarias para Composer, MySQL y PostgreSQL
RUN apt-get update && apt-get install -y \
curl \
git \
libfreetype6-dev \
libjpeg62-turbo-dev \
libpng-dev \
libwebp-dev \
libxpm-dev \
libzip-dev \
zip \
unzip \
nano \
libpq-dev \ 
&& docker-php-ext-configure gd --with-freetype --with-jpeg --with-webp \
&& docker-php-ext-install pdo pdo_mysql pdo_pgsql gd

# Instalar Composer
RUN curl -sS https://getcomposer.org/installer | php && \
mv composer.phar /usr/local/bin/composer

# Habilitar mod_rewrite y configurar Apache
RUN a2enmod rewrite

# Copiar el VirtualHost
COPY ./vhost.conf /etc/apache2/sites-available/000-default.conf

# Establecer el directorio de trabajo
WORKDIR /var/www/html

# Si no usas volumen, copia tu código
#COPY . /var/www/html

# Da permisos
RUN chown -R www-data:www-data /var/www/html \
&& chmod -R 755 /var/www/html 

# Si se usa volumen, da permisos a storage y bootstrap/cache
# && chown -R www-data:www-data /var/www/html/storage /var/www/html/bootstrap/cache \
# &&  chmod -R 775 /var/www/html/storage /var/www/html/bootstrap/cache